### ISSUE TITLE
Freeze while transmitting

### ISSUE THREAD

**Issue by peon5** [markqvist/MicroAPRS#10]
Hi,
I'm running a MicorAPRS Modem with the precompiled "microaprs-5v-ss-latest.hex" code. It worked pretty well for a few days. Now there's an issue with the transmission. If I give a serial command (beginning with "!" to transmit the modem never stops the transmission. TX is always high and the radio PPT remains pushed. 
I built an other modem with a new arduino(clone) and i got the same problem after a few days.
The other code "MicroModemGP-5v-direct.hex" seems to work. At least in terms of cutting TX.
I hope there's a fix for this problem. Besides this problem I've to say the modem setup and the ss-code is absolutely fantastic!

**Comment by bedmonson85** [comment]
I know this is an old post, but for others having the same problem, I found that I had a ground loop problem. Instead of using the mosfet to trigger the PTT directly I hooked up a small 5v reed relay and isolated the PTT ground from the rest of the circuit.  It fixed it for me.

**Comment by markqvist** [comment]
Closing this, as this is most probably ground loop or RF feedback related.
