### ISSUE TITLE
Precompiled firmware works fine (5v KISS) firmware compiled with same settings does not

### ISSUE THREAD

**Issue by tcarwash** [markqvist/MicroAPRS#12]
Running pre-compiled firmware on my DIY modem works as advertised. Compiled firmware, even if unchanged from a fresh clone of repository and no changes gives no rx.

DIY modem, 5v reference. need to change preamble_len or pre-compiled would be fine.

**Comment by markqvist** [comment]
What are you compiling this on/with?
