### ISSUE TITLE
Question about a problem I have with attached radio not opening

### ISSUE THREAD

**Issue by airikka** [markqvist/MicroAPRS#3]
Hi!

I have just built the MicroModem and I’m using the MicroAPRS firmware.
Since there is almost zero APRS traffic where I live, I connected one of my Baofengs (UV-82) to send using APRSDroid in VOX mode and it was sending from the adjancent room with low power. The MicroModem was connected to my other Baofeng (UV-5R) and when the volume was set to maximum, MicroModem/APRS decoded the messages and showed it nicely both in cutecom and xastir. I have built the “777a080″ version of your git repo, both for serial and for KISS. I guess that the 5V/3.3V reference means if the 5V or 3.3V pin on the Arduino is used against the A0. I’m using Arduino Nano and 5V, so I built for 5V reference.
But now to the strange thing. Today I made a “field test” where I went to a bigger city nearby to try it out, because there’s more APRS traffic there. The strange thing is that when the device was up and running, I could hear APRS traffic in my radio that was not connected to the MicroModem but the radio that was connected to the MicroModem did not even open (the receiver LED on the radio did not lit up). I switched radios, so the other one was connected to the MicroModem, but the result was the same, the radio that was connected to the MicroModem did not receive anything but I could hear a lot of traffic on the radio that was not connected to the MicroModem.
Do you have any idea what the source of this problem could be? It seems that the MicroModem is somehow changing the radio’s squelch behavior.

Thanks!

**Comment by markqvist** [comment]
Hi Airikka! I answered your comment on the blog as well. Please only post issues related to the software on this github page :) I'll close this one since it's more of a specific hardware issue.

**Comment by airikka** [comment]
Yes, sorry about that.
