### ISSUE TITLE
CONFIG_AFSK_PREAMBLE_LEN too short

### ISSUE THREAD

**Issue by airikka** [markqvist/MicroAPRS#4]
Hi,

The predefined value CONFIG_AFSK_PREAMBLE_LEN is, at least in my setup, too short.
I'm using aprx as digipeater software and I have not found any possibilities to get it to send CMD_TXDELAY over KISS which would override the CONFIG_AFSK_PREAMBLE_LEN.
In my setup, it's probably the receiving radio (that is in very sensitive squelch mode, instead of open squelch, to save batteries) that does not open in time if the preamble is set to 150UL and misses the first bits of the message transmitted by the aprx digipeater (which is using MicroAPRS). Or maybe it's a combination of both the transmitting radio and receiving radio that is the problem. But increasing the preamble will give the receiving radio more time to react.
I have not tested where the treshold is for my setup. I have only tested with 1000UL (successfully for a longer time) and only once with 500UL (also successfully that single time). Maybe it could be even less than 500UL, but 150UL is too short.

/airikka

**Comment by IW3IJQ** [comment]
Aprx has the parameter  "initstring" (see user manual Page 23 http://ham.zmailer.org/oh2mqk/aprx/aprx-manual.pdf). You have to enter a Kiss command frame in HEX notation.

**Comment by IW3IJQ** [comment]
Here (https://github.com/PhirePhly/aprx/issues/21) a brief explanation of aprx initstring for kiss modems.

**Comment by airikka** [comment]
Thanks IW3IJQ. I will try to change it next time I experiment with aprx.

**Comment by markqvist** [comment]
Closing this, as the preamble lenght can already be changed via KISS commands
