### ISSUE TITLE
Optimize Boolean types

### ISSUE THREAD

**Issue by IW3IJQ** [markqvist/MicroAPRS#7]
In kiss.c there are tho boolean variable defined (IN_FRAME and ESCAPE),
in this situation avr-gcc take 2 bytes to store 2 bit (chek in map file after compilation).

A better approach could be as explaned here:
http://www.avrfreaks.net/comment/318337#comment-318337

**Comment by markqvist** [comment]
Thanks for the suggestion, that would indeed be an optimization. I am not going to implement this though, since it's way too much work to save 1 byte of RAM for now.

Thanks anyways though!
